plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'

    // jib 플러그인
    id 'com.google.cloud.tools.jib' version '3.4.0'
}

group = 'org.sopt'
version = '0.0.1-SNAPSHOT'
description = 'web1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    testImplementation 'io.projectreactor:reactor-test'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 헬스 체크
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // 테스트 컨테이너용 DB
    runtimeOnly 'com.h2database:h2'
    // Swagger 의존성
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14'

    implementation platform('software.amazon.awssdk:bom:2.17.230')
    implementation 'software.amazon.awssdk:s3'

    // 2. JSON 처리 (필수)
    // Spring Boot에 보통 포함되어 있지만, 명시적으로 추가하여 버전 관리 보장
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // 3. 비동기 처리를 위한 AOP (필수, @Async 작동)
    implementation 'org.springframework.boot:spring-boot-starter-aop'
}

jib {
    from {
        image = 'eclipse-temurin:17-jdk'
    }
    to {

        image = project.hasProperty('jibToImage') ? project.getProperty('jibToImage') : 'docker.io/default-user/default-repo'

        // 태그 설정: 입력받은 태그(run-id)와 'latest' 태그를 동시에 푸시하도록 설정
        tags = project.hasProperty('jibTag')
                ? [project.getProperty('jibTag'), 'latest']
                : ['latest']

        if (project.hasProperty("dockerHubUsername") && project.hasProperty("dockerHubPassword")) {
            auth {
                username = project.findProperty("dockerHubUsername").toString()
                password = project.findProperty("dockerHubPassword").toString()
            }
        }
    }
    container {
        jvmFlags = ["-Xms512m", "-Xmx512m"]
        creationTime = "USE_CURRENT_TIMESTAMP"
        format = 'Docker'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
